hmcts/hwf-publicapp

app/assets/stylesheets/application.scss
app/assets/stylesheets/local/tables.scss
app/views/home/summary.html.slim

[Pivotal](https://www.pivotaltracker.com/story/show/112592235)
Summary page styling (not confirmation page, as mentioned on Pivotal - that's the page after this one).
All links ("Change" and the green button) go to # at the moment.

basic styling for summary page

---

app/controllers/home_controller.rb
app/views/home/marital_status.html.slim
config/application.rb
config/locales/en.yml
spec/features/pages/question_one_spec.rb

To do this, an error block is added to session and then re-loaded
on reloading the page.  On successful submission of the form, the
session variable is cleared.
I've added a proposal for feature tests by page to handle routing 
and error handling.  Happy to discuss, and possibly move back into
the uber feature tests if that is preferred.
This should probably be reviewed by:
@dotemacs as usual,
@axemonkey to check my css usage, and 
@leighmoney to check my words!

Added marital_status error handling

---

app/assets/javascripts/application.js

Forgot this - needs to be included for `<details>` elements to work in non-Webkit browsers.

add details polyfill

---

app/views/home/marital_status.html.slim
app/views/home/summary.html.slim
config/locales/en.yml
config/locales/questions.yml
config/locales/summary.yml

This is a proposal for splitting the locale files for ease of use
The idea is that, ultimately, there will be the following files:
**en.yml** General file, activemodel, generic messaging
**question.yml** The text from the question pages grouped by subject
**summary.yml** Text for display on the summary page
Happy to discuss at any time...

Split locale files

---

config/locales/questions.yml

It's only reserved in the Ruby language, but not in the localisation
names.

Using 'case' correctly

---

app/views/home/national_insurance.html.slim

The extra info `<details>` panel for NI was missed out when creating the app content.

extra NI info that was left out

---

app/assets/javascripts/modules/uppercase-fields.js
app/views/home/national_insurance.html.slim

Previously the css transform was showing the user uppercase letters, but lowercase were still being sent to the server, and failing validation. Now the transform is only applied if JS is present, and if it is, the value is uppercased by JS when focus leaves the field.

uppercase the NI field value with JS

---

app/controllers/home_controller.rb
app/models/national_insurance.rb
app/models/views/summary.rb
app/views/home/national_insurance.html.slim
app/views/home/summary.html.slim
config/locales/en.yml
config/locales/questions.yml
config/locales/summary.yml
spec/features/pages/national_insurance_question_spec.rb
spec/models/national_insurance_spec.rb
spec/models/views/summary_spec.rb

tl;dr National Insurance validation works
While trying to update the error handling I realised that what we did not return the values to the page.  This worked fine while we only had unfilled checkboxes, but text fields needed something extra!
I have refactored the home controller to store all values in session[:model]['attribute'] and session[:model_errors]
We can now store multiple values and errors per model, while still loading them at the end of the process.
Now when a text value is invalid, the inputted text is returned to the user.

Improved error handling via the NI page

---

app/models/claim.rb
app/views/home/claim.html.slim
app/views/home/summary.html.slim
config/locales/en.yml
config/locales/questions.yml
config/locales/summary.yml
spec/controllers/home_controller_spec.rb
spec/models/claim_spec.rb

Added attribute 'identifier' to Claim model which is meant to hold the
form number name in case the user chooses the option that states
that (s)he has made a case/claim/'notice to pay'.
Added tests for it and updated the locales.

Case number extras

---

app/services/localise.rb
spec/services/localise_spec.rb

Why: I wanted to clean up the Base class that all the objects inherit
from which has the i18n_scope method, as I feel that this functionality
violates the single responsibility principle.

Locale helper

---

spec/rails_helper.rb

This means that travis (as it sets ENV['RACK_ENV'] to 'test') will still display them, but they won't run on local machines

Hide rspec.profile_examples locally

---

app/models/dob.rb

I had the minimum & maximum age declared as constants. But:
'A constant in Ruby is like a variable, except that its value is
supposed to remain constant for the duration of a program.'
They would never be updated after the initial load of the program. The
reason we haven't stumbled upon this bug just yet is because we deploy
pretty frequently.
Bug caught by Dan Palmer. All hail Dan.
/cc @dan-palmer

Age calculation fix

---

config/locales/questions.yml

The yml did not have an http prefix so the link was being rendered
as: http://our-site/gov.uk/child-tax-credit-when-child-reaches-16
not: https://www.gov.uk/child-tax-credit-when-child-reaches-16

Updated link to gov.uk page

---

app/assets/javascripts/modules/income-table.js

[Pivotal](https://www.pivotaltracker.com/n/projects/1212124/stories/115027201)
Before the columns weren't totalling if the user's cursor was still in a value entry field. This fixes that.
Before
---
After
---

fix for JS totalling bug

---

config/locales/summary.yml
spec/features/apply_for_help_with_fees_spec.rb
spec/features/user_details_are_not_persisted_spec.rb

1. removed ‘send’ from button and statement of truth so that applicants
don’t think that the application is complete (as they need to send the
ref number to the court)
2. changed ‘ no contact requested’ to ‘contact details not provided’

Tweaks to summary copy

---

app/assets/javascripts/modules/income-table.js

Bug found by @firstaide – the JS calculcation events were being triggered on all `.form-control` fields on the income page, including the Other Income Description field, resulting in a `NaN` value when tabbing out of it. This fixes that by restricting the JS to fields with `type="number"`.

only do calculations on number fields

---

app/controllers/home_controller.rb
app/views/home/index.html.slim
config/routes.rb
spec/features/apply_for_help_with_fees_spec.rb
spec/features/user_details_are_not_persisted_spec.rb

Because we don't know if our system will be rendering the start page, or if it will be served from GOV.UK, we can't have a dynamic form on it. So the start button becomes just a GET link again, until that decision is made. 
Also I think clearing out session in a GET method is not a good practice, so I've just narrowed it down to be cleared when the data is submitted in the end. The start button session clearing was useful for the user testing, but there's no real need. The session should have a reasonably short expiration itself, to prevent multiple users on the same computer to potentially access their data.

Clear session only when complete

---

.gitignore
Makefile
nightwatch
package.json
tests/nightwatch/commands/ensureCorrectPage.js
tests/nightwatch/commands/nextPage.js
tests/nightwatch/commands/radioSelect.js
tests/nightwatch/commands/startService.js
tests/nightwatch/commands/testShowHideCheckbox.js
tests/nightwatch/commands/testShowHideRadio.js
tests/nightwatch/custom_assertions/doesNotContainText.js
tests/nightwatch/custom_assertions/urlNotEqual.js
tests/nightwatch/local.json
tests/nightwatch/modules/log.js
tests/nightwatch/specs/happypath-test-show-hide.js
tests/nightwatch/specs/income-table.js

Have added Nightwatch to the public app to help catch JS regressions. Tests provided for the show/hide functionality and the JS income table.
No CI integration at the moment, but at least it's here. Could be added to CI at some point in the future, but requires a running rails instance to run the tests against (we have the same situation with the staff app).

Nightwatch

---

app/assets/javascripts/modules/external-links.js
app/views/home/index.html.slim

The gov.uk template CSS adds a new window icon to any links with `rel="external"`, so this line of jQuery adds the HTML attribute `target="_blank"` so that they actually do open in a new window/tab.

external links in new window

---

app/models/contact.rb
app/models/online_application.rb
app/models/views/summary.rb
app/views/home/summary.html.slim
app/views/questions/_contact.html.slim
config/locales/questions.yml
spec/features/apply_for_help_with_fees_spec.rb
spec/features/pages/applicant_address_question_spec.rb
spec/features/pages/contact_question_spec.rb
spec/features/pages/summary_spec.rb
spec/models/contact_spec.rb
spec/services/online_application_builder_spec.rb
spec/support/feature_steps.rb
tests/nightwatch/commands/startService.js
tests/nightwatch/specs/happypath-test-show-hide.js
tests/nightwatch/specs/income-table.js

Contact page now only has one field - email - which should be optional, plus a "I can be contacted for research purposes" opt-in checkbox.
[See the corresponding page in the prototype](http://ministryofjustice.github.io/fr-prototypes/public/journey-7/contact.html).
Before
---
After
---
Back-end work required
===
* I've visually repurposed the existing email checkbox from the old version. This may or may not need renaming - I assume something will need doing here so that the app records the opt-in value
* The validation on here is from the old version, so it doesn't work correctly i.e. if you check the box, and fill in a malformed email address, the validation triggers *but* if you don't check the box, the validation doesn't trigger (because in the old version the email address field would …

front-end for contact page changes

---

app/models/base.rb
app/views/questions/_applicant_address.html.slim
app/views/questions/_benefit.html.slim
app/views/questions/_claim.html.slim
app/views/questions/_contact.html.slim
app/views/questions/_dependent.html.slim
app/views/questions/_dob.html.slim
app/views/questions/_fee.html.slim
app/views/questions/_form_name.html.slim
app/views/questions/_income.html.slim
app/views/questions/_marital_status.html.slim
app/views/questions/_national_insurance.html.slim
app/views/questions/_personal_detail.html.slim
app/views/questions/_probate.html.slim
app/views/questions/_savings_and_investment.html.slim
spec/models/base_spec.rb

Turns off autocomplete for each of the questions in non-dev environments.
That was an optional thing, but simple to remove if unnecessary!
Unfortunately it seems that browsers remember you choices even if you turn this off. :/

Turn off autocomplete

---

Gemfile
Gemfile.lock
app/assets/stylesheets/local/lists.scss
app/controllers/submissions_controller.rb
app/models/online_application.rb
app/views/submissions/show.html.slim
config/locales/en_confirmation.yml
spec/controllers/submissions_controller_spec.rb
spec/features/user_submits_their_application_spec.rb
spec/models/online_application_spec.rb
spec/support/feature_steps.rb

Different confirmation page depending on whether the application is a refund or not.
Refund version should look like it does [in the prototype](http://ministryofjustice.github.io/fr-prototypes/public/journey-7/confirmation-refund.html).

New copy for refund confirmation

---

app/views/submissions/show.html.slim
config/locales/en_confirmation.yml

[Pivotal](https://www.pivotaltracker.com/story/show/116519385)
A back to start button, on the confirmation page.
NB: links to `root_path`, which works fine locally and probably on demo/staging envs, but will probably need to do something different when it goes properly live. I think?

add back to start button to confirmation page

---

app/assets/stylesheets/confirmation-print.scss
app/views/submissions/show.html.slim

I think some bits of the print stylesheet PR got reverted in a merge conflict, or something.
Anyway, this fixes the print stylesheet. Checked and verified :+1: in latest Chrome and Firefox plus IE8, 9 and 10.

fix print stylesheet oddness

---

.codeclimate.yml

By disabling a single engine, we seem to have turned off all checks!
This enables the default engines, but still disables the fixme check.

Updated codeclimate engines

---

app/assets/stylesheets/local/buttons.scss
app/controllers/sessions_controller.rb
app/views/home/summary.html.slim
app/views/questions/edit.html.slim
app/views/shared/_restart_application_link.html.slim
config/locales/en.yml
config/routes.rb
spec/controllers/sessions_controller_spec.rb
spec/features/user_can_restart_application_spec.rb
spec/support/feature_steps.rb

All question pages and the summary page get `Start a new application` link (button) at the bottom, which clears the session and redirects to the home page.
The form is in a single partial `app/views/shared/_restart_application_link.html.slim`.

Add ability to restart application

---

app/models/forms/income.rb
spec/models/forms/income_spec.rb

This is for a case when the user doesn't provide any specific income.
But because the UI still displays 0 as a sum, we can affort to do this
temporarily to fix a bug on income calculation (fr-staffapp).

Return 0 income instead of nil

---

config/locales/en_terms.yml

Due to a copy/paste artefact there was a disclaimer at the beginning and end of the page
After checking with @leighmoney, removed heading from the top of the page.

remove duplicate disclaimer heading

---

app/controllers/application_controller.rb
app/controllers/submissions_controller.rb
app/services/storage.rb
app/views/layouts/application.html.slim
spec/controllers/submissions_controller_spec.rb
spec/services/storage_spec.rb

This will need testing on demo before it's merged!
This adds a ga_events collection to application controller, then any controller can call 
```ruby
ga_events << "ga('send', 'field', 'foo', 'bar')"
```
This will be processed by a slim embedded javascript block on the layout to submit events to GA.

Add timing to Google analytics

---

app/assets/javascripts/modules/income-table.js

This was actually reported as an iPad bug, but it affected desktop too.
On step 5, income, if an amount was entered into any box then an error triggered, the page would reload and show each amount with a single decimal. (To trigger an error, enter a description for other income but no amount.)
Before
---
After
---

format values on page load

---

app/models/forms/applicant_address.rb
app/models/forms/claim.rb
app/models/forms/contact.rb
app/models/forms/dependent.rb
app/models/forms/form_name.rb
app/models/forms/income.rb
app/models/forms/personal_detail.rb
app/models/forms/probate.rb
app/views/questions/forms/_personal_detail.html.slim
config/locales/en.yml
spec/models/forms/applicant_address_spec.rb
spec/models/forms/claim_spec.rb
spec/models/forms/contact_spec.rb
spec/models/forms/dependent_spec.rb
spec/models/forms/form_name_spec.rb
spec/models/forms/income_spec.rb
spec/models/forms/personal_detail_spec.rb
spec/models/forms/probate_spec.rb

This came out of security / load testing, that our fields should be restricted in what they can accept. 
Essentially the problem is that the encrypted cookie session is quite limited in size, so trying to store very long fields will crash it. We may need to consider using an alternative cookie storage if that becomes too much of an issue.

Restrict field character length

---

.env.test
app/controllers/health_status/health_check_controller.rb
app/controllers/health_status/ping_controller.rb
app/services/health_status/deployment.rb
app/services/health_status/health_check.rb
app/services/submit_application.rb
config/routes.rb
config/settings.yml
spec/controllers/health_status/health_check_controller.rb
spec/controllers/health_status/ping_controller_spec.rb
spec/services/health_status/deployment_spec.rb
spec/services/health_status/health_check_spec.rb
spec/services/submit_application_spec.rb

Adding the `/ping.json` and `/healthcheck.json` end-points. 
* `ping.json` contains deployment information (if available)
* `healthcheck.json` contains status of the service and its downstream dependencies
As opposed to our `fr-staffapp` I namespaced this functionality and added more tests. My original idea was to take this whole thing to an engine gem, which would allow mounting it to other MoJ projects as well. But that can be done separately when we have some time.

Healthcheck end-points

---

app/views/layouts/application.html.slim

The GA script is now on top of the layout before the <html> tag, which is not W3C compliant. Also if there's a problem with loading the script, it could slow down the whole page.

Move GA script to the footer

---

app/assets/javascripts/modules/income-table.js

fixing a minor JS niggle - only format currency value if there is one

prevent NaN console message on income table when tabbing

---

app/controllers/application_controller.rb
app/services/storage.rb
app/views/home/index.html.slim
app/views/questions/edit.html.slim
app/views/summaries/show.html.slim
config/locales/en.yml
config/settings.yml
spec/features/session_expires_when_inactive_spec.rb
spec/features/user_submits_their_application_spec.rb
spec/services/storage_spec.rb
spec/support/feature_steps.rb

The user has 10 minutes of inactivity before the session expires. There's no warning of that happening at the moment, only an error after. There will be a subsequent story on the backlog to improve this. 
It's mostly a prerequisite for us to be able to improve the confirmation page.
Also I think it's time to start thinking about the `Storage` class and maybe how can we split it into smaller and simpler services / classes. It's getting quite chunky and maybe it has too much responsibility. I'll do so in the following work.

Session time out

---

config/locales/en.yml
spec/features/pages/fee_question_spec.rb

When a refund date is entered for the future the error message wasn't displaying correctly.
[screenshot](https://www.pivotaltracker.com/file_attachments/62230159/download?inline=true)
Added a test for the correct handling and then updated the locale file to display the proper message
[Pivotal ticket](https://www.pivotaltracker.com/story/show/120938009)

Update future refund error handling

---

app/models/forms/fee.rb

This was a bug when the today's date for refund was cached on app server
start.

Always use current date for refund calculation

---

app/views/questions/forms/claim/_default.html.slim

They got wrong when the question become dynamic based on standard / ET
flow. Now they're fixed for the standard flow.

Fix claim number form labels

---

app/assets/stylesheets/local/typography.scss
app/views/questions/forms/_dob.html.slim
app/views/questions/forms/_fee.html.slim
app/views/questions/forms/_probate.html.slim
config/locales/questions.yml

[Pivotal](https://www.pivotaltracker.com/story/show/120178605)
When I came to test this in JAWS 17 I found that it was in fact reading out the second slash, but not the fourth Y, so I was hearing "D D slash M M slash Y Y Y edit" (edit meaning that this was an editable text box, and was expected)
This PR inserts spaces between each character, which makes JAWS read the format hint correctly, then uses CSS `letter-spacing` to visually drag the characters back together.

fix date format in hints for screenreaders

---

app/assets/javascripts/modules/external-links.js
app/assets/stylesheets/local/links.scss

At the moment the only clue that a link will open in a new window is a visual icon, which is no good to blind users.
This expands the JS by adding a text warning about this to both the title attribute of the link, and the link text itself (using the `visuallyhidden` CSS class).
Additionally, since we are applying `target="_blank"` to these links, it's advisable to also add `rel="noopener"`, because [security](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/). Unfortunately, the gov.uk elements CSS for external links didn't support multiple values on the `rel` attribute, so some CSS patching was needed.

New window warning

---

app/views/home/index.html.slim
app/views/summaries/show.html.slim
config/locales/questions.yml
config/locales/summary.yml
spec/features/pages/summary_spec.rb

Add hidden text to the 'Change' links on the summary page, and lengthen links to 'the guide'.

Fix single word/short links

---

app/views/questions/edit.html.slim
app/views/shared/_error_block.html.slim

Our error summary title is a `<h1>` tag, as is our main page title or question. Making the error summary title into a `<h2>` tag, means it should go after the `<h1>`.
Thoughts?
Before
---
After
---

Make errors H2, move below H1

---

app/views/questions/forms/_income.html.slim
app/views/summaries/show.html.slim

[Pivotal mentions that the summary page table has no caption](https://www.pivotaltracker.com/story/show/121287999), as reported by DAC, so this provides one as well as one for the table on the income entry page.

add captions to tables

---

config/locales/questions.yml

Change from ‘can’ to ‘will’ to meet DAC recommendations.

DAC amend for email notification

---

Gemfile
Gemfile.lock
README.md

Due to a code injection warning in [CVE-2015-8806](http://www.cvedetails.com/cve/CVE-2015-8806/)

Update nokogiri gem

---

app/assets/javascripts/modules/form-name.js

The "form name unknown" box is programatically unchecked when the user starts typing a form name or number. It should also remove the `selected` CSS class from the label.

unhighlight checkbox label when JS unchecks box

---

app/assets/stylesheets/local/tables.scss
app/views/summaries/show.html.slim

[Pivotal - DAC recommendation](https://www.pivotaltracker.com/story/show/123104281)
Changes the first `td` in each row of the check details table to `th scope="row"` in order to give structure to the table, as recommended by DAC.

row headers for summary table

---

app/controllers/sessions_controller.rb
app/services/storage.rb
config/routes.rb
config/settings.yml
spec/controllers/sessions_controller_spec.rb
spec/services/storage_spec.rb

* If an external url is set via ENV, home page is always redirected there (there's no test for this as it uses conditional routes and it doesn't seem to be easily possible with RSpec), better solution may be done later
* All data is cleared when `/session/start` is accessed (the apply button either from the homepage or the gov.uk page)

Make homepage external

---

app/assets/stylesheets/local/utilities.scss
app/views/home/index.html.slim
spec/features/can_user_apply_for_help_with_fees_spec.rb
spec/support/feature_steps.rb

[Pivotal](https://www.pivotaltracker.com/story/show/121658901)
Even though the live version of this page will be outside the live app, it's still good to have it here as a record. There is some debate about whether GDS can use the `<details>` expandable elements in their templates.

update start page with expandable regions

---

app/views/home/index.html.slim
config/locales/questions.yml
public/400.html
public/404.html
public/500.html

Start page
— links to guide and form
Benefits
— small typo on benefit name
Income
— link to guide
400 / 404 /500
— link to form

Fix broken links to PDFs

---

app/views/questions/forms/_fee.html.slim
app/views/questions/forms/_probate.html.slim

[Pivotal - DAC recommendation](https://www.pivotaltracker.com/story/show/123080931)
We introduced visually hidden full stops to prevent screen readers running sentences together in input labels. It transpires that this just sticks out as an error to real screen reader users. They are used to sentences with little separation between them, and this extra element intended to help them in fact just looks like it shouldn't be there.

Remove visually hidden full stops

---

app/views/questions/edit.html.slim
app/views/questions/forms/_applicant_address.html.slim
app/views/questions/forms/_benefit.html.slim
app/views/questions/forms/_contact.html.slim
app/views/questions/forms/_dependent.html.slim
app/views/questions/forms/_dob.html.slim
app/views/questions/forms/_fee.html.slim
app/views/questions/forms/_form_name.html.slim
app/views/questions/forms/_marital_status.html.slim
app/views/questions/forms/_national_insurance.html.slim
app/views/questions/forms/_personal_detail.html.slim
app/views/questions/forms/_probate.html.slim
app/views/questions/forms/_savings_and_investment.html.slim
app/views/questions/forms/_savings_and_investment_extra.html.slim
app/views/questions/forms/claim/_default.html.slim
app/views/questions/forms/claim/_et.html.slim

[Pivotal - DAC recommendation](https://www.pivotaltracker.com/story/show/121582181)
[Second pivotal ticket covered by this PR](https://www.pivotaltracker.com/story/show/121581909)
We were blanket enclosing all form fields groups in a fieldset with a legend per page. The fieldset tag is only meant for grouping related form controls, so in cases where there is only a single input box no fieldset is needed, and in other cases the fieldset should only enclose groupe/related fields.

Only use <fieldset>s where appropriate

---

app/assets/stylesheets/local/inputs.scss

Hints were showing with no space on non-local envs due to minified HTML versus pretty HTML. Go figure.
This fixes the display of these so that they are not dependent on HTML whitespace.

fix for hint display

---

app/views/questions/forms/_income_kind.html.slim
app/views/questions/forms/_income_range.html.slim

In creating the new income flow, some old `<legend>` tags got left in and not updated. Also, on IE8, the fact that a `<legend>` is only valid inside a `<fieldset>` meant that the browser ignored the CSS, and displayed the text of the tag rather than keeping it `visuallyhidden`.
`<fieldset>`s have been added and the text of the `<legend>`s has been corrected.
Fixes [this Pivotal bug](https://www.pivotaltracker.com/story/show/126577453).

missing fieldsets on new income pages

---

app/models/forms/base_range.rb
app/models/forms/income_range.rb
app/models/forms/savings_and_investment.rb
app/models/online_application.rb
app/models/views/summary.rb
app/services/clear_downstream_questions.rb
app/services/navigation.rb
app/views/summaries/show.html.slim
spec/factories/online_applications.rb
spec/features/apply_for_help_with_fees_spec.rb
spec/features/pages/income_question_spec.rb
spec/models/forms/base_range_spec.rb
spec/models/forms/income_range_spec.rb
spec/models/forms/savings_and_investment_spec.rb
spec/models/views/summary_spec.rb
spec/services/clear_downstream_questions_spec.rb
spec/services/navigation_spec.rb
spec/support/feature_steps.rb

This is an improvement on the income flow, which skips the 3rd page when the user earns either less or more than the thresholds. If they earn between the thresholds, the 3rd page is displayed. 
For this to work, the https://github.com/ministryofjustice/fr-staffapp/pull/697 has to be merged first..

Support income range

---

app/assets/javascripts/application.js
app/assets/javascripts/details.polyfill.iecompatible.js

We use [the details polyfill from GOV.UK elements](https://github.com/alphagov/govuk_elements/blob/master/public/javascripts/vendor/details.polyfill.js) to make the `<details>` elements work in all browsers. However the DAC found a problem, in that a keyboard user cannot expand a `<details>` element using the enter/return key, and has to use the space bar. Pressing enter/return submits the form.
To work around this I created a local copy of the polyfill and patched it to work as expected in all browsers (IE9 and up – IE8 works as before, i.e. the `<details>` element functions with mouse and with space bar). Tested and working with both space bar and enter/return key.

fix details element in IE so it opens on enter

---

app/assets/stylesheets/local/typography.scss
app/views/questions/edit.html.slim

Splits the step info e.g. "Step 2 of 20" out of the page's main `<h1>` tag since having it inside the `<h1>` was causing at least one screen reader to report multiple level 1 headings on the page.

split step info out of H1 tag

---

app/services/health_status/health_check.rb
spec/services/health_status/health_check_spec.rb

Added downstream_api to public health check, this looks at the staff app and returns the overall staff health check result and bubble the results up to pingdom.
Leaving healthy? as a standalone method still allows the public to submit applications, while allowing us to alert to failures of both the staff and public apps via pingdom.

Extend the healthchecks

---

app/models/views/summary.rb
app/views/summaries/show.html.slim
config/locales/en_post_welsh.yml
spec/features/pages/summary_spec.rb
spec/features/user_switches_from_benefits_but_avoids_income_spec.rb
spec/models/views/summary_spec.rb
spec/support/feature_steps.rb

We are receiving data in the staff app in an invalid state
The only way we can replicate the state is to complete a benefits application and, via the change and back buttons, set benefits to false and return to the summary page.
Add validation to the summary object and alert users to issues that need rectifying.
* There are plans to implement dynamic routing of questions in the future, but that is outside the current support scope.
* the weird name of the yaml file is to prevent conflicts with the welsh-version branch being merged

Validate benefit income

---

app/models/views/summary.rb
spec/features/user_switches_from_benefits_but_avoids_income_spec.rb
spec/models/views/summary_spec.rb
spec/support/feature_steps.rb

The previous PR fixed the main issue but missed a subset of applications.
This adds tests for the extra validation scenario and then implements the fix.

Validate income fix

---

app/services/navigation.rb
app/services/question_form_factory.rb
spec/features/pages/probate_question_spec.rb
spec/services/navigation_spec.rb
spec/services/question_form_factory_spec.rb

[Trello ticket](https://trello.com/c/aqCOKk0f/15-skip-step-8-probate-case-if-employment-tribunal)
[Original pivotal - for detail](https://www.pivotaltracker.com/n/projects/1212124/stories/121044203)
When a user has chosen ET as an option at question 1 there is no need to ask if it's a probate question later.
This handles both methods of routing to ensure the requirement.

Remove probate from ET flow

---

app/views/summaries/show.html.slim

The question was moved to second but the summary answer was
still in the original sequence and looked out of place

Move the fee/refund summary line

---

app/controllers/confirmations_controller.rb
spec/controllers/confirmations_controller_spec.rb

In certain circumstances, session did not have a start time.
This caused an error when calculating the time taken for the GA stats...
Added a handler to return 0 if started? or time_taken had not been set properly

Add handler for nil time_taken

---

app/controllers/confirmations_controller.rb
spec/controllers/confirmations_controller_spec.rb

Expire the pages after the session/storage has cleared.
In the tests, explicitly set the started? value to allow tests
to accurately handle the storage clearance

Handle expiry of confirmation pages

---

app/views/questions/forms/_savings_and_investment_extra.html.slim

Users were struggling to get the correct format for the extra savings field 
> , with  a comma, without, with pound sign, without etc. 
This adds a number field type to the input, it prevents text, `£`, etc, yet still allows `3,000.00` style entries.
It is what we use on the income input field, so this provides a standard approach to the fields

Add `number` type to savings field

---

app/views/layouts/application.html.slim

In the welsh language merge, the link got overwritten incorrectly

Corrected feedback link

---

spec/rails_helper.rb

Fixing issue with a randomly failing test.

Setting local to en (was empty) for tests.

---

features/step_definitions/step_eighteen_steps.rb
features/step_definitions/step_fifteen_steps.rb
features/step_definitions/step_seventeen_steps.rb
features/support/page_objects/step_fifteen_page.rb
features/support/page_objects/step_seventeen_page.rb

Tests were passing in Chrome but failing when run using a headless browser. 
Strings are read slightly differently so I have separated the strings:
'Title (Optional)'
'Email address (Optional)'
to expect:
'Title'
'Email address'
'(Optional)'

small changes for step 15 and 17

---

README.md
features/README.md

Markdown headings must have a space between the hash and the title.

Fix and link to feature test README

---

.env.test
Dockerfile.saucelabs
bin/run_saucelabs
features/support/capybara_driver_helper.rb
features/support/env.rb
features/support/saucelabs/browsers.yml

This PR includes the Dockerfile for running the saucelabs test and some adjustments in few files to fit the container's needs. Also, it includes some clean up refactoring.
Warning: The CI is using the official saucelabs connect plugin to setup the tunnel, meaning that further setup is required to run this container on a local machine.

Create Dockerfile for running saucelabs tests

---

performance-tests/src/test/resources/application.conf

This allows to define dynamically the environment the Gatling tests will run against, with localhost being the default one.

Use env var for the application's base url in Gatling

---

features/step_definitions/common_steps.rb
features/step_definitions/step_twelve_steps.rb
features/step_four.feature
features/step_seven.feature
features/step_six.feature
features/step_thirteen.feature
features/step_three.feature
features/step_twelve.feature
features/support/capybara_driver_helper.rb
features/support/page_objects/common_page.rb
features/support/page_objects/step_twelve_page.rb

Removed ignore hidden elements from capybara helper as advised by Gary.
It broke some tests relating to 'Help with...' and 'Cancel application'. These have been fixed.
Further refactoring is recommended but out of scope for this task.

Removed ignore hidden elements from capybara helper

---

Gemfile
Gemfile.lock
features/step_definitions/zap_security_steps.rb
features/support/capybara_driver_helper.rb

Added geckodriver-helper
Updated Gemfile.lock
Changed scenario.title to scenario.name as advised on below
`#title is deprecated and will be removed after version 2.9.9. Call #name instead.`
Fixed step When I take the happy path through steps 1 to 20

Fix for running ZAP Cucumber test in Firefox

---

app/models/forms/help_request.rb
app/services/zendesk_sender.rb
app/views/help_requests/new.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/controllers/help_requests_controller_spec.rb
spec/models/forms/help_request_spec.rb
spec/services/zendesk_sender_spec.rb

We want to remove the telephone number field to prevent users providing their telephone number and expecting a phone cal from the Help with Fees staff.

Ask user's email instead of their phone in the ask for help page

---

app/helpers/yaml_helper.rb
config/locales/en.yml

The anchor was after the heading which in Safari and Chrome looked like you are in the middle of paragraph not in the beginning.

Fixing anchor bug and adding italic styling.

---

app/controllers/application_controller.rb
app/controllers/confirmations_controller.rb
app/services/storage.rb
app/views/layouts/application.html.slim
app/views/shared/_analytics.html.slim
spec/controllers/confirmations_controller_spec.rb
spec/services/storage_spec.rb

HWF will be using to use Google Tag Manager for managing Google Analytics events.
So, this PR replaces the GA snippet with the Tag Manager one and removes any custom GA code from the backend.

RST 1250 Google Tag Manager

---

Gemfile
Gemfile.lock

Update gem 'selenium-webdriver' and 'geckodriver-helper' to fix this error:
newSession (Selenium::WebDriver::Error::UnknownError)
WebDriverError@chrome://marionette/content/error.js:179:5
UnknownCommandError@chrome://marionette/content/error.js:473:5

gem update to fix firefox driver issue

---

app/views/questions/forms/_national_insurance.html.slim
config/locales/cy.yml
config/locales/en.yml
features/step_definitions/national_insurance_steps.rb
features/support/page_objects/national_insurance_page.rb

There is no clear guidance on the digital channel for citizens who don't have a NI number. This statement directs them to complete a paper form, which is correct and agreed process.

RST-1773 Updating text on NI number page to help users

---

config/settings.yml
spec/features/pages/form_name_question_spec.rb
spec/features/pages/income_question_spec.rb

To make sure that if the ENV value for probate switch is not there we are still not going to switch it on.

Changing the alternative date if the env is missing

---

app/views/layouts/moj_template.html.erb

https://tools.hmcts.net/jira/browse/RST-2781
This PR adds back the head section in the moj_template. 
All the `content_for :head` will be rendered again.
```
[ ] Yes
[X] No
```

Add the missing head section in the moj_template

---

Gemfile.lock

There is a possible shell escape sequence injection vulnerability in the Lint
and CommonLogger components of Rack. This vulnerability has been assigned the
CVE identifier CVE-2022-30123.

Rack update

---

Gemfile.lock

Name: rexml
Version: 3.3.1
Advisory: CVE-2024-39908
Criticality: Unknown
URL: https://github.com/ruby/rexml/security/advisories/GHSA-4xqq-m2hx-25v8
Title: DoS in REXML
Solution: upgrade to '>= 3.3.2'

RST-6787 - update rexml to 3.3.2
