hmcts/hwf-publicapp

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/views/layouts/application.html.erb
=> Remove Turbolinks

Dockerfile, README.md, config/unicorn.rb
Added Unicorn & Docker configs
=> Unicorn & Docker config

.travis.yml, spec/rails_helper.rb
Added the code climate key and configured the rails helper.
=> Added code climate

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/home.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/home.scss, app/views/layouts/application.html.slim, config/application.rb, config/initializers/assets.rb
Basic front-end skeleton inc header/footer, js setup, css imports etc
=> add frontend toolkit, import stylesheets

README.md
Added the badges for Code Climate & Travis CI
=> Updated the Readme with badges

app/controllers/home_controller.rb, app/models/applicant_address.rb, app/models/base.rb, app/models/benefits.rb, app/models/case_number.rb, app/models/fee_paid.rb, app/models/form_name.rb, app/models/marital_status.rb, app/models/national_insurance.rb, app/models/personal_details.rb, app/models/probate_case_fee.rb, app/models/savings_and_investments.rb, config/routes.rb, spec/models/applicant_address_spec.rb, spec/models/benefits_spec.rb, spec/models/case_number_spec.rb, spec/models/fee_paid_spec.rb, spec/models/form_name_spec.rb, spec/models/national_insurance_spec.rb, spec/models/personal_details_spec.rb, spec/models/probate_case_fee_spec.rb, spec/models/savings_and_investments_spec.rb
I've created all but two models for the whole app. Why? So that we can see where the repetition is (because there will be some, and there is) and to get this app done quicker.
Now what's left:
* adding the controllers
* adding the views
* sorting out the persistence (into the session)
The missing models are:
* Contact: http://ministryofjustice.github.io/fr-prototypes/public/journey-7/contact.html
* DOB: http://ministryofjustice.github.io/fr-prototypes/public/journey-7/dob.html
=> More work, more models

config/application.rb, config/secrets.yml, lib/secret_token.rb
To allow Docker to run, it needs a secret key.
=> Add SecretToken

Gemfile, Gemfile.lock, app/controllers/home_controller.rb, app/models/savings_and_investment.rb, app/services/navigation.rb, app/views/home/savings_and_investment.html.slim, app/views/home/summary.html.slim, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/features/apply_for_help_with_fees_spec.rb, spec/models/savings_and_investment_spec.rb, spec/services/navigation_spec.rb
In order to move between forms, added Navigaton service.
Reorganised the features, the reasoning is that its all one big
story. Done it in a messy war for now, because I just want it to
work. Then I'll revisit it later.
Added Web Console for debugging.
=> Added Savings & Investment form

app/controllers/home_controller.rb, app/models/views/summary.rb, app/services/navigation.rb, app/views/home/form_name.html.slim, app/views/home/summary.html.slim, spec/controllers/home_controller_spec.rb, spec/features/apply_for_help_with_fees_spec.rb, spec/models/views/summary_spec.rb, spec/services/navigation_spec.rb
Handle routing, display and summary
The details block works in Chrome, but firefox will need
the JS polyfill fix applied
=> Added form_name

app/controllers/home_controller.rb, app/services/navigation.rb, app/views/home/national_insurance.html.slim, app/views/home/summary.html.slim, spec/controllers/home_controller_spec.rb, spec/features/apply_for_help_with_fees_spec.rb, spec/services/navigation_spec.rb
And all the required plumbing for it to work
=> Added the National Insurance form

app/assets/javascripts/application.js, app/assets/javascripts/modules/radio-buttons.js, app/assets/stylesheets/application.scss, app/views/home/marital_status.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/112879739)
=> styling and minimal js for marital status page

app/views/home/savings_and_investment.html.slim
[Le Pivotal](https://www.pivotaltracker.com/story/show/113432433)
More of the same. Not sure why it says Question 2 of 14 though.
=> Styling for savings and investments page

app/controllers/home_controller.rb, app/models/personal_detail.rb, app/models/views/summary.rb, app/services/navigation.rb, app/views/home/personal_detail.html.slim, app/views/home/summary.html.slim, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/features/apply_for_help_with_fees_spec.rb, spec/models/personal_detail_spec.rb, spec/models/views/summary_spec.rb, spec/services/navigation_spec.rb
And the related plumbing to make it render, along with the examples
=> Personal details

app/assets/stylesheets/local/typography.scss, app/views/home/benefit.html.slim
=> styling for benefits page

app/views/home/marital_status.html.slim, app/views/home/savings_and_investment.html.slim, app/views/shared/_error_block.html.slim, config/locales/en.yml, spec/features/pages/question_two_spec.rb
Added error handling for the savings page.
Retro fitted the new error_block partial into the marital_status view.
=> Error handling savings

app/views/home/fee.html.slim
=> style fee page

app/views/home/probate.html.slim
=> style probate page

app/views/home/benefit.html.slim, config/locales/en.yml, config/locales/questions.yml, spec/features/pages/question_three_spec.rb
* moved text to summary and question.yam
* feature tests
=> Updated benefit page

app/views/home/fee.html.slim, app/views/home/summary.html.slim, config/locales/en.yml, config/locales/questions.yml, config/locales/summary.yml, spec/features/pages/fee_question_spec.rb
* moved text to summary and question.yam
* feature tests
+ minor fixes to summary to align with standard approach
=> Updated fee page

app/views/home/claim.html.slim
=> style claim number page

app/models/base.rb, app/views/home/benefit.html.slim, app/views/home/fee.html.slim, app/views/home/marital_status.html.slim, app/views/home/savings_and_investment.html.slim, app/views/home/summary.html.slim, config/locales/en.yml, config/locales/questions.yml, config/locales/summary.yml, spec/features/pages/fee_question_spec.rb, spec/features/pages/question_three_spec.rb
Updated the savings and investment page to use the new locale structures
Added a method to the base class to make calling the new structure easier
Refactored the marital_status page to use the new base method
=> Update locale files

app/models/base.rb, app/views/home/benefit.html.slim, app/views/home/fee.html.slim, app/views/home/marital_status.html.slim, app/views/home/savings_and_investment.html.slim, spec/models/base_spec.rb
Refactor i18n_scope
* Used class.name rather than class.to_s
* added test for method
Updated views with errors to apply styles to correct level
=> Error fixes

app/views/home/summary.html.slim, config/locales/en.yml, config/locales/summary.yml
I noticed that I missed an obvious summary string!
=> Updated summary yaml

app/assets/stylesheets/local/utilities.scss, app/views/home/national_insurance.html.slim
This was a nice little feature in the staff app that Foundation provided.
=> uppercase transform on NI field

app/assets/stylesheets/application.scss, app/assets/stylesheets/local/inputs.scss, app/views/home/personal_detail.html.slim
=> styling for full name page

app/views/home/applicant_address.html.slim
=> styling for address page

spec/features/pages/fee_question_spec.rb, spec/features/pages/probate_question_spec.rb
Some of the question features were mis-labelled
=> corrected the mis-labelled files

app/assets/javascripts/application.js, app/assets/javascripts/modules/show-hide.js, app/assets/stylesheets/local/utilities.scss, app/views/home/contact.html.slim, vendor/assets/javascripts/govuk_show-hide-content.js
[Pivotissimos](https://www.pivotaltracker.com/story/show/113811755)
=> styling and show/hide for contact page

app/views/home/contact.html.slim
=> missing paragraph from contact page

Gemfile, Gemfile.lock, app/models/fee.rb, app/models/views/summary.rb, app/views/home/fee.html.slim, app/views/home/summary.html.slim, config/initializers/date_time.rb, config/locales/en.yml, spec/controllers/home_controller_spec.rb, spec/features/pages/fee_question_spec.rb, spec/models/fee_spec.rb
Added a fee_paid attribute to the fee model.
Duplicated validation from the staff app and added tests for obvious scenarios
This will need to be refactored into three date fields but after discussing with @jitenp this is the MVP implementation!
=> Refund extra field

app/views/home/fee.html.slim
Only show the date fee paid field if Yes is selected.
=> conditional reveal for date fee paid field

app/models/base.rb, app/models/fee.rb, app/models/probate.rb, app/models/views/summary.rb, app/views/home/probate.html.slim, app/views/home/summary.html.slim, config/locales/en.yml, config/locales/summary.yml, spec/controllers/home_controller_spec.rb, spec/features/pages/probate_question_spec.rb, spec/models/probate_spec.rb
Extended the probate model, added deceased's name and date of death.
Imported validation and messaging from staffapp.
=> Added fields to probate

app/views/home/fee.html.slim, app/views/home/probate.html.slim
=> Probate page show hide

app/views/home/form_name.html.slim, config/locales/en.yml, config/locales/questions.yml
Added error messages for the form on the form page 9.
Also added localisation messages.
=> Added errors & added localised messages for step 9

app/views/layouts/application.html.slim
=> correct copy for phase bar

app/models/personal_detail.rb, app/views/home/personal_detail.html.slim, config/locales/en.yml, config/locales/questions.yml, spec/features/pages/national_insurance_question_spec.rb, spec/features/pages/personal_details_question_spec.rb, spec/models/personal_detail_spec.rb
* moved text to yml
* added feature tests for question
After discussion with team, removed the mandatory presence of title
=> Updated personal-details

app/views/home/applicant_address.html.slim, app/views/home/national_insurance.html.slim, config/locales/en.yml, config/locales/questions.yml, spec/features/pages/applicant_address_question_spec.rb
* moved text to yml
* added feature tests for question
=> Updated applicant-address

app/views/home/claim.html.slim
=> showy hidey claimy numbery fields

app/models/views/summary.rb, app/views/home/contact.html.slim, app/views/home/summary.html.slim, config/locales/en.yml, config/locales/questions.yml, config/locales/summary.yml, spec/features/apply_for_help_with_fees_spec.rb, spec/features/pages/applicant_address_question_spec.rb, spec/features/pages/contact_question_spec.rb
* moved text to yml
* added feature tests for question
=> Updated contact

app/assets/stylesheets/local/inputs.scss, app/views/home/claim.html.slim, app/views/home/probate.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/114382955)
Before
---
After
---
=> fix error field stylings

app/views/home/national_insurance.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/114486993)
=> correct error message id

app/assets/javascripts/modules/income-table.js, app/assets/stylesheets/local/inputs.scss, app/assets/stylesheets/local/tables.scss, app/views/home/income.html.slim
[Pivotal](https://www.pivotaltracker.com/story/show/113911003)
=> income page front end work

app/models/dob.rb, config/locales/en.yml, spec/models/dob_spec.rb
Amended the minimum age an applicant can be in order to make an
application after a discussion with Leigh & Adrian.
Added test coverage for all the validation messages.
=> Updated DOB model

app/models/form_name.rb, spec/models/form_name_spec.rb
No more validation, as per feature request:
https://www.pivotaltracker.com/projects/1212124/stories/113811783
=> Removed validation on Form Name object

config/locales/questions.yml, spec/features/pages/national_insurance_question_spec.rb, spec/features/pages/personal_details_question_spec.rb
* updated the hint text [pivotal](https://www.pivotaltracker.com/story/show/114483945)
also, renamed the tests so that the file names were corrected!
[finishes #114483945]
=> Updated NI page

app/assets/javascripts/application.js, app/assets/stylesheets/local/inputs.scss, app/assets/stylesheets/local/tables.scss, vendor/assets/javascripts/is-nan.polyfill.js
Screenshots replaced after latest amends:
Large
---
Medium
---
Small
---
=> tweak income table for small screens

config/locales/questions.yml
As we can accept dates in a certain format only, have added hint text.
May need styling.
=> Added hint text to this question

app/views/home/dependent.html.slim, config/locales/en.yml, config/locales/questions.yml
This makes it consistent with the way help is presented for other
questions - also provides more detail as this is a complex area.
=> Added help to question 4

app/views/home/income.html.slim, config/locales/questions.yml
Added info on what should be included as income; added links to the
guide.
=> Updated income guidance

app/views/home/summary.html.slim, config/locales/summary.yml
Added links back to appropriate sections on summary page, so that the
users can go back and edit their entries.
=> Added links on summary page

app/views/home/income.html.slim, config/locales/questions.yml
missed this bit off the previous PR, because idiot.
=> copy for non-JS users

app/views/home/index.html.slim, spec/features/can_user_apply_for_help_with_fees_spec.rb
[Pivotal](https://www.pivotaltracker.com/story/show/115328183)
=> copy updates to start page

app/views/home/income.html.slim, config/locales/questions.yml
[Pivotal](https://www.pivotaltracker.com/story/show/115411651)
Before
---
After
---
=> copy update for income page guidance

app/views/home/dob.html.slim, app/views/home/fee.html.slim, app/views/home/probate.html.slim, config/locales/questions.yml
a single date field text box confuses users unless they are told the required date format
=> add date format hint text

app/assets/stylesheets/confirmation-print.scss, app/views/submissions/show.html.slim, config/initializers/assets.rb
=> Print stylesheet for confirmation page

app/assets/stylesheets/local/typography.scss
=> fix double underline

app/assets/stylesheets/local/inputs.scss, app/views/questions/_contact.html.slim, config/locales/questions.yml
[Pivotal](https://www.pivotaltracker.com/story/show/116530625)
1.
2.
=> Front end tweeks

config/application.rb
Set the Rails application config feedback url to the google form url
=> Add feedback link

app/controllers/home_controller.rb, app/helpers/yaml_helper.rb, app/views/home/terms_and_conditions.html.slim, app/views/layouts/application.html.slim, config/locales/en_terms.yml, config/routes.rb, spec/controllers/home_controller_spec.rb
Adds a terms and conditions page to the public app
Uses a structured YAML approach that allows a helper to recursively walk the tree of YAML and output the required tags.
[Test me](https://terms-and-conditions.hwf.dsd.io/terms_and_conditions)
[Pivotal ticket](https://www.pivotaltracker.com/story/show/116140109)
=> Add terms and conditions

app/assets/stylesheets/local/phase-banner.scss, config/application.rb
=> short answer: we're in beta

app/assets/stylesheets/application.scss, app/assets/stylesheets/local/links.scss, app/views/home/summary.html.slim, app/views/questions/edit.html.slim, app/views/questions/forms/_benefit.html.slim, app/views/questions/forms/_fee.html.slim, app/views/questions/forms/_marital_status.html.slim, app/views/questions/forms/_probate.html.slim, app/views/questions/forms/_savings_and_investment.html.slim, app/views/submissions/show.html.slim
A run through of accessibility gotchas using the WAVE extension for Chrome highlighted a couple of dumb things, like no H1 tags. Doh.
=> Accessibility review

app/views/questions/forms/_dob.html.slim
`label` can't contain `div`, but can contain `span`.
=> w3c html compliance fix

app/models/forms/national_insurance.rb, spec/models/forms/national_insurance_spec.rb
Updated the public validation of NI to match the staff side
[pivotal](https://www.pivotaltracker.com/story/show/118639531)
=> Update NI validation to remove spaces

app/assets/stylesheets/local/utilities.scss, app/views/submissions/show.html.slim, config/locales/en_confirmation.yml
=> Add feedback link to the confirmation page

app/views/home/index.html.slim, config/locales/questions.yml
Fixed broken link to guide on income page
Changed capitalisation of form number on index page
=> update guide link

config/locales/en_confirmation.yml, config/locales/questions.yml, config/locales/summary.yml
This is a bug fix to the current release.
=> Increment total number of steps in the breadcrumbs

app/views/confirmations/done.html.slim, app/views/confirmations/et.html.slim, app/views/confirmations/refund.html.slim, app/views/confirmations/show.html.slim, app/views/help_requests/new.html.slim, app/views/home/terms_and_conditions.html.slim, app/views/questions/edit.html.slim, app/views/summaries/show.html.slim, config/application.rb, config/locales/en_confirmation.yml, config/locales/en_help_requests.yml, config/locales/en_terms.yml, config/locales/questions.yml, config/locales/summary.yml
[Pivotal](https://www.pivotaltracker.com/story/show/120178065)
Create unique page titles for pages in the app to aid AT users, and anyone who uses their history and/or back button. 👍
=> Page titles

public/400.html, public/404.html, public/500.html
As per recent additions from @joshlow on [Pivotal](https://www.pivotaltracker.com/story/show/120962735)
=> add links to paper form to the error pages

app/models/forms/savings_and_investment_extra.rb, config/locales/en.yml, config/locales/questions.yml, spec/models/forms/savings_and_investment_extra_spec.rb, spec/models/views/summary_spec.rb
* change the validation to between 3000 and 15999
* update the labels and tests to account for the changes
[Pivotal comment](https://www.pivotaltracker.com/story/show/118632405/comments/137594275)
=> Update savings thresholds

Gemfile, Gemfile.lock
@novotnyjakub. Added sentry-raven gem to gemfile.
=> add sentry gem to gemfile

config/application.rb, config/locales/en_confirmation.yml
Changes to:
— survey link to updated survey questions
— text link to improve responses
=> Change to survey link and text

app/views/questions/forms/_applicant_address.html.slim, app/views/questions/forms/_benefit.html.slim, app/views/questions/forms/_contact.html.slim, app/views/questions/forms/_dependent.html.slim, app/views/questions/forms/_dob.html.slim, app/views/questions/forms/_fee.html.slim, app/views/questions/forms/_form_name.html.slim, app/views/questions/forms/_marital_status.html.slim, app/views/questions/forms/_national_insurance.html.slim, app/views/questions/forms/_personal_detail.html.slim, app/views/questions/forms/_probate.html.slim, app/views/questions/forms/_savings_and_investment.html.slim, app/views/questions/forms/_savings_and_investment_extra.html.slim, app/views/questions/forms/claim/_default.html.slim, app/views/questions/forms/claim/_et.html.slim
It wasn't a huge problem, but it was i) irritating and ii) inconsistent. 
Before
---
After
---
=> don't write out empty error span tags

app/assets/stylesheets/local/inputs.scss, app/views/questions/forms/_contact.html.slim, app/views/questions/forms/_personal_detail.html.slim
=> add (optional) to optional fields

app/views/home/index.html.slim
— savings threshold is less than 16k for you or partner
— make it clear that no savings is valid
— update benefit conditions for consistency
=> Clarify points on start page

app/models/forms/claim/et.rb, app/views/summaries/show.html.slim, spec/models/forms/claim/et_spec.rb
Applications were rejected when ET didn't answer the probate question.
=> Set probate to false if ET claim number completed

.travis.yml, package.json
* Update the selenium package version
* ensure phantomJS version is always set to 2.1.1
* cache and pre-install in travis
This addresses minor issues raised by Gemnasium
=> Update npm handling

app/controllers/questions_controller.rb, public/400.html, public/404.html, public/500.html
Ensure static.css has `/` prefix on the static html pages
Show a 404 page when questions error
=> Make error pages work

app/models/forms/probate.rb, spec/models/forms/probate_spec.rb
JIRA ticket: https://triadmoj.atlassian.net/browse/RST-27
It looks like validation block was not evaluated each time which causes a validation error.
=> Date validation is now using actual time value as it's called each time.

Gemfile, Gemfile.lock
This downgrade will fix the fields not appearing in IE 8 bug.
Ticket: [RST-58](https://triadmoj.atlassian.net/browse/RST-58)
=> downgrade Uglifier gem version

app/helpers/application_helper.rb, app/views/confirmations/et.html.slim, spec/features/pages/user_can_apply_for_et_case_spec.rb
Making sure that English translation is hidden for step 3 on a confirmation page.
https://triadmoj.atlassian.net/browse/RST-133
=> Making sure that step3 copy is displayed only in Welsh.

.env.development, config/settings.yml, lib/probate_fees_switch.rb, spec/lib/probate_fees_switch_spec.rb, spec/support/probate_fees_switchover_helper.rb
**Note: Please do not merge this PR, until further notice.**
=> create the switch for the probation fees changes

app/helpers/application_helper.rb, app/views/confirmations/et.html.slim, config/locales/cy.yml, spec/features/pages/user_can_apply_for_et_case_spec.rb
Welsh translation fixes.
Tickets:
* RST-169
* RST-168
* RST-167
* RST-166
=> fix Welsh translations

features/step_definitions/common_steps.rb, features/step_definitions/step_seven_steps.rb, features/step_seven.feature, features/support/generic_helpers.rb, features/support/page_objects/common_page.rb, features/support/page_objects/step_seven_page.rb
=> RST-311 tests for step 7

features/step_definitions/common_steps.rb, features/step_definitions/step_eight_steps.rb, features/step_eight.feature, features/support/generic_helpers.rb, features/support/page_objects/step_eight_page.rb, features/support/page_objects/step_nine_page.rb
JIRA https://triadmoj.atlassian.net/browse/RST-313
=> RST-313 tests for step 8

features/step_definitions/common_steps.rb, features/step_definitions/step_eight_steps.rb, features/step_definitions/step_nine_steps.rb, features/step_definitions/step_seven_steps.rb, features/step_eight.feature, features/step_nine.feature, features/support/page_objects/common_page.rb, features/support/page_objects/step_eight_page.rb, features/support/page_objects/step_nine_page.rb
https://triadmoj.atlassian.net/browse/RST-316
=> RST-316 tests for step nine

features/step_definitions/common_steps.rb, features/step_definitions/step_eight_steps.rb, features/step_definitions/step_five_steps.rb, features/step_definitions/step_four_steps.rb, features/step_definitions/step_one_steps.rb, features/step_definitions/step_seven_steps.rb, features/step_definitions/step_six_steps.rb, features/step_definitions/step_three_steps.rb, features/step_definitions/step_two_steps.rb
=> steps refactor

features/step_definitions/common_steps.rb, features/step_definitions/step_eleven_steps.rb, features/step_eleven.feature, features/step_ten.feature, features/support/generic_helpers.rb, features/support/page_objects/step_eight_page.rb, features/support/page_objects/step_eleven_page.rb, features/support/page_objects/step_five_page.rb, features/support/page_objects/step_four_page.rb, features/support/page_objects/step_nine_page.rb, features/support/page_objects/step_one_page.rb, features/support/page_objects/step_seven_page.rb, features/support/page_objects/step_six_page.rb, features/support/page_objects/step_three_page.rb, features/support/page_objects/step_two_page.rb
Tests for https://helpwithcourtfees.service.gov.uk/questions/probate?locale=en
Removed any unused selectors from the page objects (step 1 - 9)
=> RST-331 tests for step eleven

app/views/help_requests/new.html.slim
id for continue button for Cucumber tests
=> HwF | id for continue button

features/step_definitions/common_steps.rb, features/step_definitions/step_thirteen_steps.rb, features/step_thirteen.feature, features/support/generic_helpers.rb, features/support/page_objects/step_thirteen_page.rb
https://tools.hmcts.net/jira/browse/RST-347
Where: /questions/national_insurance
=> RST-347 tests for step thirteen

features/step_definitions/common_steps.rb, features/step_definitions/step_fifteen_steps.rb, features/step_definitions/step_fourteen_steps.rb, features/step_fifteen.feature, features/step_fourteen.feature, features/support/generic_helpers.rb, features/support/page_objects/common_page.rb, features/support/page_objects/step_fifteen_page.rb, features/support/page_objects/step_fourteen_page.rb
/questions/personal_detail
jira https://tools.hmcts.net/jira/browse/RST-350
=> RST 350 cucumber step fifteen

features/step_definitions/common_steps.rb, features/step_definitions/step_fourteen_steps.rb, features/step_fourteen.feature, features/support/generic_helpers.rb, features/support/page_objects/common_page.rb, features/support/page_objects/step_fourteen_page.rb
=> RST-348 tests for step fourteen

features/step_definitions/common_steps.rb, features/step_definitions/step_fifteen_steps.rb, features/step_definitions/step_sixteen_steps.rb, features/step_fifteen.feature, features/step_sixteen.feature, features/support/generic_helpers.rb, features/support/page_objects/step_fifteen_page.rb, features/support/page_objects/step_sixteen_page.rb
/questions/contact
JIRA https://tools.hmcts.net/jira/browse/RST-353
Removed 'a valid' where there is no validation in place
e.g
'I enter my title' instead of 'I enter a valid title'
=> RST-353 tests for step sixteen

features/step_definitions/common_steps.rb, features/step_eight.feature, features/step_eleven.feature, features/step_fifteen.feature, features/step_five.feature, features/step_four.feature, features/step_fourteen.feature, features/step_nine.feature, features/step_one.feature, features/step_seven.feature, features/step_six.feature, features/step_sixteen.feature, features/step_ten.feature, features/step_thirteen.feature, features/step_three.feature, features/step_twelve.feature, features/step_two.feature
Refactored step 'I am taken to step two' so that it uses two variables, the step number and the url.  This takes it down to one step instead of one for each page.   The new step checks the step number on the page and the url.
=> refactored common step

features/step_definitions/common_steps.rb, features/step_definitions/step_seventeen_steps.rb, features/step_seventeen.feature, features/support/generic_helpers.rb, features/support/page_objects/step_seventeen_page.rb
JIRA https://tools.hmcts.net/jira/browse/RST-355
/questions/contact
=> RST-355 cucumber step seventeen

features/README.md, features/smoke_tests.feature
Taken two versions of the happy path and added the scenarios to a smoke_tests.feature file.
Updated README.md to give instructions on how to run these smoke tests.
=> RST-437 added smoke tests

app/models/forms/contact.rb, app/views/questions/forms/_contact.html.slim, config/locales/en.yml, features/step_definitions/step_eighteen_steps.rb, features/step_definitions/step_nineteen_steps.rb, features/step_definitions/step_seventeen_steps.rb, features/step_definitions/step_twenty_steps.rb, features/step_eighteen.feature, features/step_seventeen.feature, spec/features/pages/contact_question_spec.rb, spec/features/pages/summary_spec.rb, spec/models/forms/contact_spec.rb
=> Applicant has to fill the email

app/views/questions/forms/_benefit.html.slim, app/views/questions/headers/_benefit.html.slim, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/step_six_steps.rb, features/step_six.feature, features/support/page_objects/step_six_page.rb
Updating the look and copy of benefits page.
=> Updating Benefit questions for en and cy.

app/views/questions/headers/_benefit.html.slim, config/locales/cy.yml, config/locales/en.yml
=> Making some words bold on benefit page.

config/routes.rb, spec/features/pages/ask_for_help_spec.rb
When you submit the form it will display error messages. Then If you switch language it would fail to render the page. I fixed it.
=> Fixing issue on ask for help form.

app/models/forms/dob.rb, app/models/forms/fee.rb, app/models/forms/probate.rb, app/views/questions/forms/_dob.html.slim, app/views/questions/forms/_fee.html.slim, app/views/questions/forms/_probate.html.slim, config/locales/en.yml, features/support/page_objects/dob_page.rb, features/support/page_objects/fee_page.rb, features/support/page_objects/probate_page.rb, spec/features/apply_for_help_with_fees_spec.rb, spec/features/pages/dob_question_spec.rb, spec/features/pages/fee_question_spec.rb, spec/features/pages/probate_question_spec.rb, spec/features/pages/summary_spec.rb, spec/models/forms/dob_spec.rb, spec/models/forms/fee_spec.rb, spec/models/forms/probate_spec.rb, spec/services/online_application_builder_spec.rb, spec/support/feature_steps.rb
Refactoring single date input field into a day/month/year fields.
=> RST-1785 -  date input fields

app/controllers/home_controller.rb, app/views/home/checklist.html.slim, app/views/home/index.html.slim, config/locales/cy.yml, config/locales/en.yml, config/routes.rb, spec/controllers/home_controller_spec.rb, spec/features/apply_for_help_with_fees_spec.rb, spec/support/feature_steps.rb
This PR introduces a new page with all the things the users need to complete the online form.
=> Add checklist page before the questions

performance-tests/src/test/resources/application.conf, performance-tests/src/test/scala/simulations/HelpWithFeesPerformance.scala
Updated test to current behaviour and changed env from local to staging.
```
[ ] Yes
[ x] No
```
=> updated gatling test to current behaviour

Dockerfile, run.sh
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> RST-2057 base image service support

app/assets/stylesheets/local/banners.scss, app/views/home/checklist.html.slim, app/views/shared/_maintenance_notice.html.slim, config/locales/cy.yml, config/locales/en.yml, config/settings.yml
https://tools.hmcts.net/jira/browse/RST-2114
This PR will add a maintenance notification on the checklist page with a switch to enable/disable it.
```
[ ] Yes
[X] No
```
=> Add maintenance notification on the checklist page

app/views/home/index.html.slim
https://tools.hmcts.net/jira/browse/RST-2060
Remove unnecessary head tag
```
[ ] Yes
[X] No
```
=> Remove H5 element from the index page

app/views/layouts/application.html.slim
https://tools.hmcts.net/jira/browse/RST-2032
Add main landmark to improve accessibility
```
[ ] Yes
[X] No
```
=> Improve accessibility for the main content

app/views/summaries/show.html.slim, features/support/page_objects/summary_page.rb
https://tools.hmcts.net/jira/browse/RST-2064
Update the summary table to be more readable by Screen Readers.
```
[ ] Yes
[X] No
```
=> Fix check details table accessibility

app/views/confirmations/done.html.slim, app/views/confirmations/show.html.slim, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/confirmation_done_steps.rb, features/step_definitions/confirmation_steps.rb, features/support/page_objects/confirmation_done_page.rb, features/support/page_objects/confirmation_page.rb
https://tools.hmcts.net/jira/browse/RST-2103
Add missing main headers in the confirmation pages (Steps 19 and 20)
```
[ ] Yes
[X] No
```
=> Add main headers in the confirmation pages

app/views/questions/forms/_applicant_address.html.slim, app/views/questions/forms/_benefit.html.slim, app/views/questions/forms/_contact.html.slim, app/views/questions/forms/_dependent.html.slim, app/views/questions/forms/_fee.html.slim, app/views/questions/forms/_income_kind.html.slim, app/views/questions/forms/_income_range.html.slim, app/views/questions/forms/_marital_status.html.slim, app/views/questions/forms/_personal_detail.html.slim, app/views/questions/forms/_probate.html.slim, app/views/questions/forms/_savings_and_investment.html.slim, app/views/questions/forms/_savings_and_investment_extra.html.slim, app/views/questions/forms/claim/_default.html.slim, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-2063
Remove fieldset captions to avoid repetition
```
[ ] Yes
[X] No
```
=> Remove fieldset captions to avoid content repetition

app/helpers/income_helper.rb, app/views/questions/headers/_income_amount.html.slim, app/views/questions/headers/_income_range.html.slim, config/locales/en.yml, features/income_amount.feature, features/income_range.feature
https://tools.hmcts.net/jira/browse/RST-1793
To improve the clarity of the question asked.
```
[ ] Yes
[x] No
```
=> rst-1793 - Updating copy for wages and income

app/views/questions/forms/_dob.html.slim, app/views/questions/forms/_fee.html.slim, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-2062
Fixing orphaned form labels to improve accessibility 
```
[ ] Yes
[x] No
```
=> Fixing orphaned form labels

app/views/help_requests/new.html.slim
https://tools.hmcts.net/jira/browse/RST-2516
Updating styles 
```
[ ] Yes
[x] No
```
=> RST-2516 - Updating styling for Ask for help page

Gemfile, Gemfile.lock, config/application.rb, spec/rails_helper.rb
https://tools.hmcts.net/jira/browse/RST-2145
```
[ ] Yes
[X] No
```
=> Send metrics to Azure Application Insights

features/support/hooks.rb, spec/rails_helper.rb
RST-2145
This will stub any requests to Azure Application Insights when running tests.
```
[ ] Yes
[X] No
```
=> Stub cucumber requests to Azure Application Insights

app/models/forms/home_office.rb, config/locales/en.yml, features/home_office.feature, features/step_definitions/home_office_steps.rb, features/support/page_objects/home_office_page.rb, spec/models/forms/home_office_spec.rb
https://tools.hmcts.net/jira/browse/RST-2523
```
[ ] Yes
[x] No
```
=> RST-2523 HO reference number format

app/helpers/application_helper.rb, app/models/online_application.rb, app/services/clear_downstream_questions.rb, app/views/layouts/application.html.slim, app/views/summaries/show.html.slim, config/locales/en.yml, features/step_definitions/summary_steps.rb, features/summary.feature, features/support/page_objects/home_office_page.rb, features/support/page_objects/summary_page.rb, spec/services/clear_downstream_questions_spec.rb
https://tools.hmcts.net/jira/browse/RST-2524
```
[ ] Yes
[x] No
```
=> RST-2524 Home office number flow

features/support/env.rb
=> stub request for app insights 

app/views/home/checklist.html.slim, config/locales/cy.yml, config/locales/en.yml, features/benefit.feature, features/checklist.feature, features/income_amount.feature, features/income_kind.feature, features/income_range.feature, features/probate.feature, features/step_definitions/checklist_steps.rb, features/support/page_objects/checklist_page.rb, features/support/page_objects/claim_page.rb, spec/features/pages/probate_question_spec.rb, spec/features/pages/user_can_not_apply_for_et_case_spec.rb
https://tools.hmcts.net/jira/browse/RST-2544
Updating copy
```
[ ] Yes
[x] No
```
=> RST-2544 copy changes

config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/claim_page.rb, spec/features/pages/claim_question_spec.rb
=> Fixing missing copy.

app/views/questions/headers/_home_office.html.slim, app/views/questions/headers/_national_insurance_presence.html.slim, features/support/page_objects/home_office_page.rb, features/support/page_objects/national_insurance_presence_page.rb
=> Fixing hints

config/locales/en.yml, features/income_kind.feature, features/support/page_objects/claim_page.rb
=> RST-2563 - Updating copy

Dockerfile
Use the correct ruby v2.5.8 base image
```
[ ] Yes
[X] No
```
=> Fix ruby base image

config/locales/cy.yml
=> RST-2566 welsh copy changes

config/locales/en.yml, features/step_definitions/home_office_steps.rb
https://tools.hmcts.net/jira/browse/RST-2577
Link update for consistency
```
[ ] Yes
[x] No
```
=> RST-2577 Updating paper form link

app/models/forms/income_kind.rb, app/models/online_application.rb, spec/factories/online_applications.rb, spec/models/forms/income_kind_spec.rb
https://tools.hmcts.net/jira/browse/RST-2573
```
[ ] Yes
[x] No
```
=> RST-2573 - Sending income kind data via API

app/services/zendesk_sender.rb, spec/services/zendesk_sender_spec.rb
so requester has an email.
https://tools.hmcts.net/jira/browse/RST-2629
```
[ ] Yes
[x] No
```
=> RST-2629 - Updating Zendesk API call

config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-2756
```
[ ] Yes
[x] No
```
=> RST-2756 - Updating email address on policy page

app/helpers/yaml_helper.rb, app/views/home/terms_and_conditions.html.slim, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-2779
```
[ ] Yes
[x] No
```
=> RST-2779 - Updating style for terms and condition page

app/views/questions/forms/_savings_and_investment_extra.html.slim, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/savings_and_investment_extra_steps.rb
https://tools.hmcts.net/jira/browse/RST-2795
```
[ ] Yes
[x] No
```
=> RST-2795 - Adding hint for saving amount

app/views/questions/forms/_home_office.html.slim
https://tools.hmcts.net/jira/browse/RST-2873
Edited form label HTML for accessibility.
```
[ ] Yes
[x] No
```
=> Fix home office html to give form label

app/views/questions/forms/_probate.html.slim, config/locales/cy.yml, config/locales/en.yml, features/probate.feature, features/step_definitions/probate_steps.rb, features/support/page_objects/probate_page.rb
https://tools.hmcts.net/jira/browse/RST-2911
```
[ ] Yes
[x] No
```
=> RST-2911 Adding date of death label to probate page

app/models/forms/home_office.rb, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/home_office_steps.rb, features/support/page_objects/home_office_page.rb, spec/models/forms/home_office_spec.rb, spec/services/clear_downstream_questions_spec.rb, spec/services/navigation_spec.rb
https://tools.hmcts.net/jira/browse/RST-3035
```
[ ] Yes
[x] No
```
=> RST-3035 Home office number requires 7 digits now

app/views/questions/forms/_savings_and_investment.html.slim, app/views/questions/headers/_savings_and_investment.html.slim, config/locales/cy.yml, config/locales/en.yml, features/savings_investment.feature, features/step_definitions/savings_and_investment_steps.rb, features/support/page_objects/savings_investment_page.rb
https://tools.hmcts.net/jira/browse/RST-3038
- Changes to content on the saving and investments page.
```
[ ] Yes
[x] No
```
=> RST-3038 Updating saving investments page

app/views/layouts/application.html.slim, app/views/layouts/moj_template.html.erb, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-3018
- Adding Welsh translation of accessibility statement.
- Change the footer links to their respective Welsh translation.
```
[ ] Yes
[x] No
```
=> RST-3018 Welsh accessibility statement

azure-pipelines.yml
JIRA https://tools.hmcts.net/jira/browse/RST-3134
=> RST-3134 - Updating pipeline config

app/controllers/home_controller.rb, app/views/home/privacy_policy.html.slim, app/views/home/terms_and_conditions.html.slim, app/views/layouts/application.html.slim, config/locales/cy.yml, config/locales/en.yml, config/routes.rb, features/checklist.feature, features/step_definitions/checklist_steps.rb, spec/controllers/home_controller_spec.rb, spec/features/pages/terms_and_conditions_spec.rb
https://tools.hmcts.net/jira/browse/RST-3079
https://tools.hmcts.net/jira/browse/RST-3080
- Terms and conditions text updated
- Privacy policy page added
- Welsh text added
```
[ ] Yes
[x] No
```
=> RST-3079 and 3080 Privacy and Terms content changes

config/locales/cy.yml
https://tools.hmcts.net/jira/browse/RST-3145
- Added a few missing Welsh translation phrases.
```
[ ] Yes
[x] No
```
=> RST-3145 Add missing Welsh translations

app/views/home/checklist.html.slim, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-3161
- Added text about providing accurate information.
```
[ ] Yes
[x] No
```
=> RST-3161 - Additional text on "What you will need" page

Gemfile, Gemfile.lock, config/locales/en.yml, features/README.md, pipeline-steps/test-application.yaml
https://tools.hmcts.net/jira/browse/RST-1162
- Added Brakeman security gem to pipeline
```
[ ] Yes
[x] No
```
=> RST-1162 Adding Brakeman security scanner gem

config/initializers/filter_parameter_logging.rb
https://tools.hmcts.net/jira/browse/RST-3213
```
[ ] Yes
[x] No
```
=> RST-3213 - Filter out sensitive information from logs

app/controllers/sessions_controller.rb, app/views/confirmations/_footer.html.slim, app/views/layouts/moj_template.html.erb, config/application.rb, config/locales/cy.yml, config/locales/en.yml, features/confirmation_done.feature, features/step_definitions/confirmation_done_steps.rb, features/support/page_objects/confirmation_done_page.rb, spec/controllers/sessions_controller_spec.rb, spec/features/apply_for_help_with_fees_spec.rb
https://tools.hmcts.net/jira/browse/RST-2851
```
[ ] Yes
[x] No
```
=> RST-2851 smart survey

config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/contact_page.rb
https://tools.hmcts.net/jira/browse/RST-3215
=> RST-3215 Updating copy on step 19

app/views/confirmations/done.html.slim, config/locales/cy.yml, config/locales/en.yml, features/confirmation_done.feature, features/step_definitions/confirmation_done_steps.rb, features/support/page_objects/confirmation_done_page.rb
https://tools.hmcts.net/jira/browse/RST-3216
=> RST-32156 Adding link to courtfinder

Dockerfile, Gemfile.lock, README.md
=> Updating mimemagic gem

config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-3317
=> RST-3317 - cookie banner update

package-lock.json, package.json
https://tools.hmcts.net/jira/browse/RST-3394
=> RST-3394 - Updating to latest govuk-frontend version

app/views/home/cookies.html.slim, app/views/questions/edit.html.slim
https://tools.hmcts.net/jira/browse/RST-3105
=> RST-3105 Updating error message position

azure-pipelines.yml
https://tools.hmcts.net/jira/browse/RST-3397
=> RST-3397 Updating ubuntu version

config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/home_office_page.rb
https://tools.hmcts.net/jira/browse/RST-3389
=> RST-3389 HO number hint update

app/assets/javascripts/modules/address-lookup.js, app/views/questions/forms/_address_lookup.html.erb, config/locales/cy.yml, config/locales/en.yml, features/address.feature, features/support/page_objects/address_page.rb, spec/features/pages/applicant_address_question_spec.rb
https://tools.hmcts.net/jira/browse/RST-3163
=> RST-3163 Adding missing translation

app/models/online_application.rb
https://tools.hmcts.net/jira/browse/RST-3443
=> RST-3443 Fixing issue with missing address

app/controllers/submissions_controller.rb, app/services/submit_application.rb, config/locales/cy.yml, config/locales/en.yml, spec/controllers/submissions_controller_spec.rb, spec/services/submit_application_spec.rb
https://tools.hmcts.net/jira/browse/RST-3212
=> RST-3212 notify policy

config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/checklist_page.rb, features/support/page_objects/home_office_page.rb
https://tools.hmcts.net/jira/browse/RST-3091
https://tools.hmcts.net/jira/browse/RST-3065
=> RST-3091 and RST- ho number text

app/views/questions/headers/_benefit.html.slim, config/locales/cy.yml, config/locales/en.yml, config/settings.yml, features/benefit.feature, features/income_range.feature, spec/models/views/income_thresholds_spec.rb, spec/models/views/summary_spec.rb, spec/support/feature_steps.rb
https://tools.hmcts.net/jira/browse/RST-3425
https://tools.hmcts.net/jira/browse/RST-3695
=> RST-3425 and RST-3695- Updating income threshold values

app/views/questions/headers/_income_range.html.slim, config/locales/cy.yml, config/locales/en.yml, spec/features/pages/income_question_spec.rb
Changed content and removed some content for the income_range page.
```
[ ] Yes
[ X] No
```
=> RST-3932 Content changes for income page

app/views/questions/headers/_income_range.html.slim, config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/income_range_page.rb
https://tools.hmcts.net/jira/browse/RST-4021
=> RST-4021 Updating refund version of income range page

config/locales/cy.yml
https://tools.hmcts.net/jira/browse/RST-3506
=> RST-3506 Updating welsh translation for paper flow

app/views/questions/headers/_income_amount.html.slim, config/locales/en.yml, features/step_definitions/income_amount_steps.rb, features/support/page_objects/income_amount_page.rb
https://tools.hmcts.net/jira/browse/RST-4030
=> RST-4030 Updating income amount copy for english

config/locales/cy.yml
https://tools.hmcts.net/jira/browse/RST-4030
=> RST-4030 - income page Welsh version update

app/views/questions/forms/_income_range.html.slim, config/locales/cy.yml, config/locales/en.yml
Added the needed content for the page 'How much income did you receive last month?'.
```
[ ] Yes
[ X] No
```
=> RST-4068 Added content for page 'Income Range'

app/views/confirmations/refund.html.slim, config/locales/cy.yml, config/locales/en.yml
* https://tools.hmcts.net/jira/browse/RST-4193
=> RST-4193 Fixing missing claim number

app/assets/stylesheets/local/panels.scss, app/views/home/index.html.slim
Changed the content for the Get help Paying court page to be aligned with Prod. 
```
[ ] Yes
[ X] No
```
=> RST-4061 Changed content for Get help page to be aligned with Prod

config/environments/production.rb
https://tools.hmcts.net/jira/browse/RST-4378
=> RST-4378 Udpating smtp setting for sengrid

app/controllers/sessions_controller.rb
https://tools.hmcts.net/jira/browse/RST-4383
=> RST-4383 - Fixing bug for authentication token on last page

app/controllers/questions_controller.rb, app/services/page_navigation.rb, app/services/storage.rb, app/views/questions/edit.html.slim, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, spec/controllers/questions_controller_spec.rb, spec/services/storage_spec.rb
https://tools.hmcts.net/jira/browse/RST-4211
=> RST-4211 Back link functionality

config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-4346
=> RST-4346 Copy update

app/assets/stylesheets/local/utilities.scss, app/views/questions/edit.html.slim
https://tools.hmcts.net/jira/browse/RST-3525
=> RST-3525 Applying heading style for fieldset

app/assets/stylesheets/local/utilities.scss, app/views/summaries/show.html.slim, config/locales/cy.yml, config/locales/en.yml, features/summary.feature
https://tools.hmcts.net/jira/browse/RST-3826
=> RST-3826 Link to income kind page from check details page

app/views/summaries/show.html.slim
https://tools.hmcts.net/jira/browse/RST-3987
=> RST-3987 Fixing typo on translation label

Gemfile, pipeline-steps/test-application.yaml
https://tools.hmcts.net/jira/browse/RST-4690
=> RST-4690 parallel cucumber

app/views/layouts/moj_template.html.erb, package-lock.json, package.json
https://tools.hmcts.net/jira/browse/RST-4736
=> RST-4736 Updating govuk-frontend lib to latest version

app/controllers/application_controller.rb, spec/controllers/home_controller_spec.rb
https://tools.hmcts.net/jira/browse/RST-4826
=> RST-4826 Updating how the locale is set to avoid errors

app/services/clear_downstream_questions.rb, app/services/storage.rb, spec/services/clear_downstream_questions_spec.rb
https://tools.hmcts.net/jira/browse/RST-4879
=> RST-4879 Cleaning data when benefit answer is changed

package-lock.json, package.json
https://tools.hmcts.net/jira/browse/RST-5096
=> RST-5096 - Updating govuk frontend

app/models/forms/contact.rb, app/models/forms/personal_detail.rb, spec/models/forms/contact_spec.rb, spec/models/forms/personal_detail_spec.rb
https://tools.hmcts.net/jira/browse/RST-5111
=> RST-5111 Trimming white space from name and email

config/initializers/sentry.rb
https://tools.hmcts.net/jira/browse/RST-5371
=> RST-5371 Reducing transactions and removing ping

app/views/layouts/moj_template.html.erb, charts/help-with-fees-publicapp/Chart.yaml
https://tools.hmcts.net/jira/browse/RST-5494
=> RST-5494 - Update lang attribute when language change

config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/confirmation_page.rb
Reverts hmcts/hwf-publicapp#683
=> Revert "RST-5637-v2 UCD Content Change"

.gitignore, app/controllers/questions_controller.rb, app/controllers/sessions_controller.rb, app/lib/feature_switch.rb, app/models/forms/fee.rb, app/models/online_application.rb, app/services/navigation.rb, app/services/online_application_builder.rb, app/services/question_form_factory.rb, app/services/storage.rb, config/settings.yml, spec/controllers/questions_controller_spec.rb, spec/models/forms/fee_spec.rb, spec/services/question_form_factory_spec.rb
https://tools.hmcts.net/jira/browse/RST-5968
=> RST-5968 fee status

app/helpers/children_helper.rb, app/models/forms/dependent.rb, app/models/online_application.rb, app/models/views/summary.rb, app/views/questions/forms/_dependent.html.slim, app/views/questions/forms/dependents/_post_ucd.html.slim, app/views/questions/forms/dependents/_pre_ucd.html.slim, app/views/summaries/_children.html.slim, app/views/summaries/show.html.slim, config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/dependent_page.rb, spec/features/pages/benefits_question_spec.rb, spec/models/forms/dependent_spec.rb
https://tools.hmcts.net/jira/browse/RST-5972
=> RST-5972 dependents

app/controllers/submissions_controller.rb, app/controllers/summaries_controller.rb, app/models/forms/statement.rb, app/models/online_application.rb, app/models/views/summary.rb, app/views/summaries/_declaration.html.slim, app/views/summaries/show.html.slim, config/locales/cy.yml, config/locales/en.yml, spec/models/views/summary_spec.rb
https://tools.hmcts.net/jira/browse/RST-5992
=> RST-5992 declaration of truth

app/models/forms/partner_national_insurance.rb, app/models/online_application.rb, app/services/navigation_helper.rb, app/services/navigation_ni_helper.rb, app/views/questions/forms/_partner_national_insurance.html.slim, app/views/questions/headers/_partner_national_insurance.html.slim, app/views/summaries/show.html.slim, config/locales/cy.yml, config/locales/en.yml, config/settings.yml, features/step_definitions/income_kind_steps.rb, features/support/generic_helpers.rb, features/support/navigation_helper.rb, features/support/page_objects/partner_national_insurance_page.rb
https://tools.hmcts.net/jira/browse/RST-5971
=> RST-5971 NI partner

app/views/questions/headers/_income_period.html.slim, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/savings_and_investment_steps.rb, features/support/page_objects/summary_page.rb, spec/support/feature_steps.rb
=> RST-6067 income page list

app/services/address_lookup.rb, app/views/questions/headers/_applying_on_behalf.html.slim, config/locales/cy.yml, config/locales/en.yml, spec/services/address_lookup_spec.rb, spec/support/feature_steps.rb
https://tools.hmcts.net/jira/browse/RST-6069
=> RST-6069 address lookup fix

app/assets/stylesheets/local/banners.scss, app/views/questions/edit.html.slim, app/views/questions/headers/_banner.html.slim, config/locales/cy.yml, config/locales/en.yml, features/support/page_objects/base_page.rb
https://tools.hmcts.net/jira/browse/RST-5993
=> RST-5993 banner

app/models/forms/contact.rb, app/models/forms/legal_representative_detail.rb, spec/models/forms/contact_spec.rb, spec/models/forms/legal_representative_detail_spec.rb
https://tools.hmcts.net/jira/browse/RST-6087
=> RST-6087 email trim space

app/views/summaries/show.html.slim
https://tools.hmcts.net/jira/browse/RST-6104
=> RST-6104 - Fixing summary page bug

app/models/forms/dependent.rb, spec/models/forms/dependent_spec.rb
https://tools.hmcts.net/jira/browse/RST-6114
=> RST-6114 Sanitising age bands

app/services/clear_downstream_questions.rb, spec/services/clear_downstream_questions_spec.rb
https://tools.hmcts.net/jira/browse/RST-6141
=> RST-6141 Clear income period

app/assets/javascripts/application.js
https://tools.hmcts.net/jira/browse/RST-6101
=> RST-6101 jQuery update

app/models/views/summary.rb, app/services/navigation_helper.rb, app/views/summaries/show.html.slim, spec/models/views/summary_spec.rb
https://tools.hmcts.net/jira/browse/RST-6339
=> RST-6339 No benefits display for under 16

app/views/questions/edit.html.slim, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-6273
=> RST-6273 back button

config/environments/production.rb
https://tools.hmcts.net/jira/browse/RST-6269
=> RST-6269 Securing cookies

app/views/questions/forms/dependents/_post_ucd.html.slim, config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-6368
=> RST-6368 - Adding warning info to dependants page

app/models/forms/dob.rb, config/locales/cy.yml, config/locales/en.yml, spec/models/forms/dob_spec.rb
https://tools.hmcts.net/jira/browse/RST-6419
=> RST-6419 Fixing over and under 16 validation

app/models/forms/legal_representative_detail.rb, app/models/online_application.rb, app/models/views/summary.rb, app/views/questions/forms/_legal_representative_detail.html.slim, app/views/summaries/_represented_by.html.slim, config/locales/cy.yml, config/locales/en.yml, spec/models/forms/legal_representative_detail_spec.rb
https://tools.hmcts.net/jira/browse/RST-6109
=> RST-6109 Adding position at firm field

config/locales/cy.yml, config/locales/en.yml, features/step_definitions/summary_steps.rb, spec/models/forms/dob_spec.rb
https://tools.hmcts.net/jira/browse/RST-6434
=> RST-6434 Error message fix

app/services/navigation_ni_helper.rb
Possibly also fixes: RST-6470
https://tools.hmcts.net/jira/browse/RST-6483
https://tools.hmcts.net/jira/browse/RST-6470
=> RST-6483 - Fix next form step after national insurance

.rubocop.yml, app/models/forms/savings_and_investment_extra.rb, app/views/questions/forms/savings_and_investment_extra/_post_ucd.html.slim, config/locales/cy.yml, config/locales/en.yml, spec/models/forms/savings_and_investment_extra_spec.rb
https://tools.hmcts.net/jira/browse/RST-6456
=> RST-6456 Validate over 16 vs over 61 on savings page

.rubocop.yml, charts/help-with-fees-publicapp/Chart.yaml, charts/help-with-fees-publicapp/values.yaml
https://tools.hmcts.net/jira/browse/RST-6154
=> RST-6154 - Removing Zendesk reference

Gemfile, Gemfile.lock
https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman
=> Removing foreman from Gemfile

Dockerfile, Gemfile.lock
=> Minor gem updates

config/locales/cy.yml, config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-6615
=> RST-6615 Update text for NI page

charts/help-with-fees-publicapp/Chart.yaml, config/locales/cy.yml
=> RST-6721 Updated welsh translations for national insurance page

Gemfile.lock, app/views/questions/edit.html.slim, app/views/questions/headers/_banner.html.slim, config/locales/cy.yml, config/locales/en.yml
- Remove banner from fee page
- Remove translations
=> RST-6766 - remove banner from free page

package-lock.json, package.json
https://tools.hmcts.net/jira/browse/RST-6806
=> RST-6806 Minor update of gov uk library

charts/help-with-fees-publicapp/Chart.yaml, config/initializers/session_store.rb, config/settings.yml
https://tools.hmcts.net/jira/browse/RST-6960
=> RST-6960a Check if cookie domain is valid

Gemfile, Gemfile.lock, config/application.rb
https://tools.hmcts.net/jira/browse/RST-7126
=> RST-7126  Removing app insight

Gemfile.lock
=> Minor gem update

features/support/capybara_driver_helper.rb
Fixing issue with cucumber tests
=> Switching to firefox driver

Jenkinsfile_CNP, Jenkinsfile_nightly, lib/tasks/fortify.rake
https://tools.hmcts.net/jira/browse/RST-7496
=> Nightly dev

app/helpers/application_helper.rb, app/views/questions/forms/_dob.html.slim, app/views/questions/forms/_fee.html.slim, app/views/questions/forms/_probate.html.slim, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/dob_steps.rb, features/step_definitions/probate_steps.rb, features/support/page_objects/dob_page.rb, features/support/page_objects/probate_page.rb
https://tools.hmcts.net/jira/browse/RST-7601
=> RST-7601 date hint
